### ISSUE TITLE
JSON error when enabling extension

### ISSUE THREAD

**Issue by rabernat** [mozilla/jupyter-notebook-gist#53]
I am trying to follow the instructions to install and enable this extension. But I am getting the following error at the enable step:

```bash
$ jupyter nbextension enable jupyter_notebook_gist --user --py
Enabling notebook extension jupyter-notebook-gist/extension...
Traceback (most recent call last):
  File "/Users/rpa/anaconda/bin/jupyter-nbextension", line 6, in <module>
    sys.exit(notebook.nbextensions.main())
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 969, in start
    super(NBExtensionApp, self).start()
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 877, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 853, in toggle_nbextension_python
    logger=self.log)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    for nbext in nbexts]
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 345, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/manager.py", line 85, in update
    data = self.get(section_name)
  File "/Users/rpa/anaconda/lib/python2.7/site-packages/traitlets/config/manager.py", line 63, in get
    return json.load(f)
  File "/Users/rpa/anaconda/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Users/rpa/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/rpa/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/rpa/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Edit: versions:
```bash
$ jupyter --version
4.1.0
$ jupyter notebook --version
4.3.0
```

**Comment by joychak** [comment]
Having the similar issue while loading the extension -
[W 2017-01-20 16:10:06.423 xxx notebookapp:1093] Error loading server extension jupyter_notebook_gist
    Traceback (most recent call last):
      File "[...]/notebookapp.py", line 1088, in init_server_extensions
        func(self)
      File "[...]/jupyter_notebook_gist/__init__.py", line 31, in load_jupyter_server_extension
        config_manager=nbapp.config_manager,
      File "[...]/jupyter_notebook_gist/config.py", line 23, in __init__
        'oauth_client_id': self.config.NotebookGist.oauth_client_id,
      File "[...]/notebook/services/config/manager.py", line 34, in update
        return self.write_config_manager.update(section_name, new_data)
      File "[...]/traitlets/config/manager.py", line 87, in update
        self.set(section_name, data)
      File "[...]/traitlets/config/manager.py", line 78, in set
        json.dump(data, f, indent=2)
      File "[...]/json/__init__.py", line 178, in dump
        for chunk in iterable:
      File "[...]/json/encoder.py", line 422, in _iterencode
        yield from _iterencode_dict(o, _current_indent_level)
      File "[...]/json/encoder.py", line 396, in _iterencode_dict
        yield from chunks
      File "[...]/json/encoder.py", line 429, in _iterencode
        o = _default(o)
      File "[...]/json/encoder.py", line 173, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <traitlets.config.loader.LazyConfigValue object at 0x7f289a3448d0> is not JSON serializable

**Comment by jezdez** [comment]
@joychak @rabernat Can you both paste your `~/.jupyter/jupyter_notebook_config.json` and `~/.jupyter/nbconfig/notebook.json` (and redacting any security related keys) please?

**Comment by joychak** [comment]
~/.jupyter/nbconfig/notebook.json =>
{
  "load_extensions": {
    "jupyter-notebook-gist/extension": true,
    "jupyter-js-widgets/extension": true
  }
}

~/.jupyter/jupyter_notebook_config.json =>
{
  "NotebookApp": {
    "nbserver_extensions": {
      "jupyter_notebook_gist": true
    }
  }
}

But after enabling jupyter_notebook_gist, the content of the ~/.jupyter/nbconfig/notebook.json modified to =>

{
  "oauth_client_id":

**Comment by akhiljalan** [comment]
Having a similar issue. When I use $juypter notebook I get the following error message:

[I 11:46:27.277 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 11:46:28.969 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[W 11:46:29.286 NotebookApp] Error loading server extension jupyter_notebook_gist
    Traceback (most recent call last):
      File "/Users/akhiljalan/anaconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1120, in init_server_extensions
        func(self)
      File "/Users/akhiljalan/anaconda/lib/python3.6/site-packages/jupyter_notebook_gist/__init__.py", line 31, in load_jupyter_server_extension
        config_manager=nbapp.config_manager,
      File "/Users/akhiljalan/anaconda/lib/python3.6/site-packages/jupyter_notebook_gist/config.py", line 23, in __init__
        'oauth_client_id': self.config.NotebookGist.oauth_client_id,
      File "/Users/akhiljalan/anaconda/lib/python3.6/site-packages/notebook/services/config/manager.py", line 34, in update
        return self.write_config_manager.update(section_name, new_data)
      File "/Users/akhiljalan/anaconda/lib/python3.6/site-packages/traitlets/config/manager.py", line 85, in update
        data = self.get(section_name)
      File "/Users/akhiljalan/anaconda/lib/python3.6/site-packages/traitlets/config/manager.py", line 63, in get
        return json.load(f)
      File "/Users/akhiljalan/anaconda/lib/python3.6/json/__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "/Users/akhiljalan/anaconda/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/Users/akhiljalan/anaconda/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/Users/akhiljalan/anaconda/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 7 column 22 (char 184)

**Comment by mdboom** [comment]
As I'm trying to reproduce this myself, it seems it only happens if the OAuth id and secret haven't been set up in the `jupyter_notebook_config.py` file first as described in the `README`.  There's probably a way to make that edge not so sharp (somehow convey to the user that we're not set up correctly yet), but first I'd like to confirm from one of the original reporters (@rabernat, @joychak, @akhiljalan, @sammyaboum) whether the following steps resolve the issue:

1. Shut down Jupyter server
2. following the instructions [here](https://github.com/mozilla/jupyter-notebook-gist#configuration) to set up the Github OAuth tokens
3. fixing the `~/.jupyter/nbconfig/notebook.json` file to be valid JSON again by not having the trailing `oauth_client_id` line
4. restarting Jupyter
