### ISSUE TITLE
Travis-CI tests are broken

### ISSUE THREAD

**Issue by mdboom** [mozilla/jupyter-notebook-gist#58]
I think the tests have broken due to a change in external dependencies in the two years since they last ran :)

```
Traceback (most recent call last):
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py", line 50, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py", line 161, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py", line 944, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py", line 1109, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py", line 1072, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/local/lib/python2.7/site-packages/pluggy/__init__.py", line 402, in load_setuptools_entrypoints
    "Plugin %r could not be loaded: %s!" % (ep.name, e))
pluggy.PluginValidationError: Plugin 'flake8' could not be loaded: (flake8 2.6.2 (/home/travis/build/mozilla/jupyter-notebook-gist/.tox/py27/lib/python2.7/site-packages), Requirement.parse('flake8>=3.5'))!
```

Just creating the issue as a reminder to myself to look into it.

**Comment by mdboom** [comment]
Fixed by #59.
